services:
  - type: web
    name: snuffd-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
